services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: miko
      POSTGRES_PASSWORD: miko123
      POSTGRES_DB: pendapatan-daerah
    ports:
      - "8020:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  postgre_data: